// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spmjygseypjypfvdxnxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbWp5Z3NleXBqeXBmdmR4bnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjIzOTAsImV4cCI6MjA2Mjk5ODM5MH0.K1eTnCCUBZuOq4hVU3qDI9X3z22Uo56eirGgddI9lms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);